version: '3.8'

services:
  # FastAPI Backend
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: unless-stopped
    environment:
      # Database configuration - Coolify will inject these
      - DATABASE_URL=${DATABASE_URL:?Database URL is required}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - ENVIRONMENT=production
      - DEBUG=false
      - PORT=8080
      # Coolify magic environment variables
      - API_URL=${API_URL}
      - COOLIFY_URL=${COOLIFY_URL}
      - SOURCE_COMMIT=${SOURCE_COMMIT}
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - claudable-network

  # Next.js Frontend
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${API_URL}
      - PORT=3000
      # Coolify magic environment variables
      - COOLIFY_URL=${COOLIFY_URL}
      - SOURCE_COMMIT=${SOURCE_COMMIT}
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - claudable-network

networks:
  claudable-network:
    driver: bridge